config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'application#index'

    resources :clients, only: [:new, :create, :destroy]
    resources :users do
      member do
        patch :archive
      end
    end
  end

  devise_for :users
  root 'clients#index'

  resources :clients, only: [:index, :show, :edit, :update] do
    resources :tickets
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :tickets, dependent: :delete_all
  has_many :roles, dependent: :delete_all
  validates :name, presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :user
  belongs_to :client
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :client
  belongs_to :author, class_name: 'User'

  validates :subject, presence: true
  validates :details, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  scope :excluding_archived, lambda { where(archived_at: nil) }

  def to_s
  	"#{email} (#{admin? ? "Admin" : "User"})"
  end

  def archive
    self.update(archived_at: Time.now)
  end

  def active_for_authentication?
    super && archived_at.nil?
  end

  def inactive_message
    archived_at.nil? ? super : :archived
  end

end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :authorize_admin!
  def index
  end

  private

  def authorize_admin!
    authenticate_user!
    unless current_user.admin?
      redirect_to root_path, alert: "You must be an admin to do that."
    end
  end
end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < Admin::ApplicationController

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)

    if @client.save
      flash[:notice] = 'Client has been created.'
      redirect_to @client
    else
      flash.now[:alert] = 'Client has not been created.'
      render 'new'
    end
  end

  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    flash[:notice] = 'Client has been deleted.'
    redirect_to clients_path
  end

  private

  def client_params
    params.require(:client).permit(:name, :description)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :archive]
  def index
    @users = User.excluding_archived.order(:email)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
  	if @user.save
  		flash[:notice] = "User has been created."
	    redirect_to admin_users_path
	   else
	    flash.now[:alert] = "User has not been created."
	    render "new"
	   end
  end

  def show
  end

  def edit
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
    end

    if @user.update(user_params)
     flash[:notice] = "User has been updated."
      redirect_to admin_users_path
    else
      flash.now[:alert] = "User has not been updated."
      render "edit"
    end
  end

  def archive
    if @user == current_user
       flash[:alert] = "You cannot archive yourself!"
     else
       @user.archive
       flash[:notice] = "User has been archived."
     end
     
    redirect_to admin_users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :admin)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :not_authorized

  private

  def not_authorized
    redirect_to root_path, alert: "You aren't allowed to do that."
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update]

  def index
    @clients = policy_scope(Client)
  end

  def show
    authorize @client, :show?
  end

  def edit
    authorize @client, :update?
  end

  def update
    authorize @client, :update?
    if @client.update(client_params)
      flash[:notice] = 'Client has been updated.'
      redirect_to @client
    else
      flash.now[:alert] = 'Client has not been updated.'
      render 'edit'
    end
  end

  private

  def set_client
    @client = Client.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = 'The client you were looking for could not be found'
    redirect_to clients_path
  end

  def client_params
    params.require(:client).permit(:name, :description)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_client
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  def new
    @ticket = @client.tickets.build
  end

  def create
    @ticket = @client.tickets.build(ticket_params)
    @ticket.author = current_user
    
    if @ticket.save
      flash[:notice] = 'Ticket has been created.'
      redirect_to [@client, @ticket]
    else
      flash.now[:alert] = 'Ticket has not been created.'
      render 'new'
      end
  end

  def show
  end

  def edit
  end

  def update
    if @ticket.update(ticket_params)
      flash[:notice] = "Ticket has been updated."
      redirect_to [@client, @ticket]
    else
      flash.now[:alert] = "Ticket has not been updated."
      render "edit"
    end
  end

  def destroy
     @ticket.destroy
     flash[:notice] = "Ticket has been deleted."

     redirect_to @client
  end

  private

  def set_client
    @client = Client.find(params[:client_id])
  end

  def set_ticket
    @ticket = @client.tickets.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:subject, :details)
  end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/admin/clients_helper.rb
module Admin::ClientsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def admins_only(&block)
    block.call if current_user.try(:admin?)
  end

  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << 'Ticketing System').join(' - ')
      end
    end
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/admin/application/index.html.erb
<div class="row" id="admin">
  <div class="col-md-9">
    <header>
      <h1>Admin Lounge</h1>
    </header>
    <p>Welcome to Ticketee's Admin Lounge. Please enjoy your stay.</p>
  </div>
  <div class="col-md-3">
    <h2>Admin Links</h2>
    <ul class="nav nav-stacked">
      <li><%= link_to "Users", admin_users_path %></li>
    </ul>
  </div>
</div>

app/views/admin/clients/_form.html.erb
<%= simple_form_for([:admin, client]) do |f| %>
	<%= f.input :name %>
	<%= f.input :description %>

	<%= f.button :submit, class: 'btn-primary' %>
<% end %>

app/views/admin/clients/new.html.erb
<header>
<h1>New Client</h1>
</header>

<%= render 'form', client: @client %>

app/views/admin/users/_form.html.erb
<%= simple_form_for [:admin, user] do |f| %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :admin, label: 'Is an admin?' %>

  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/admin/users/edit.html.erb
<header>
	<h1>Edit User</h1>
</header>

<%= render 'form', user: @user %>

app/views/admin/users/index.html.erb
<header>
  <h1>Users</h1>

  <ul class="actions">
    <li>
      <%= link_to "New User", new_admin_user_path, class: "new" %>
    </li>
  </ul>
</header>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user, [:admin, user] %></li>
  <% end %>
</ul>

app/views/admin/users/new.html.erb
<header>
  <h1>New User</h1>
</header>

<%= render 'form', user: @user %>

app/views/admin/users/show.html.erb
<header>
	<h1><%= @user %></h1>
		<ul class="actions">
			<li>
         		<%= link_to "Edit User", [:edit, :admin, @user], class: "edit" %>
       		</li>
       		<li>
			  <%= link_to "Archive User", [:archive, :admin, @user], method: :patch,
			    data: { confirm: "Are you sure you want to archive this user?"},
			    class: "delete" %>
			</li>
    	</ul>
</header>

app/views/clients/_form.html.erb
<%= simple_form_for(client) do |f| %>
	<%= f.input :name %>
	<%= f.input :description %>
	
	<%= f.button :submit, class: 'btn-primary' %>
<% end %>

app/views/clients/edit.html.erb
<header>
	<h1>Edit Client</h1>
</header>
<%= render 'form', client: @client %>

app/views/clients/index.html.erb
<header>
<h1>Clients</h1>

<% admins_only do %>
<ul class='actions'>
<li><%= link_to 'New Client', new_admin_client_path, class: 'new' %></li>
</ul>
<% end %>

</header>

<div id='clients'>
	<% @clients.each do |client| %>
		<h2><%= link_to client.name, client %></h2>
		<p><%= client.description %></p>
	<% end %>
</div>

app/views/clients/show.html.erb
<% title(@client.name, 'Clients') %>
<header>
	<h1><%= @client.name %></h1>

	<ul class = 'actions'>
      <% if policy(@client).update? %>
		<li><%= link_to 'Edit Client', edit_client_path(@client), class: 'edit' %></li>
          <% end %>
		<% admins_only do %>
			<li><%= link_to 'Delete Client',
				admin_client_path(@client), method: :delete,
				data: { confirm: 'Are you sure you want to delete this project?' },
				class: 'delete' %></li>
		<% end %>
	</ul>
</header>

<p><%= @client.description %></p>

<header>
  <h2>Tickets</h2>
  <ul class="actions">
    <li><%= link_to 'New Ticket', new_client_ticket_path(@client), class: 'new' %></li>
  </ul>
</header>

<ul id="tickets">
  <% @client.tickets.each do |ticket| %>
      <li>
        #<%= ticket.id %> -
        <%= link_to ticket.subject, [@client, ticket] %>
      </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <title>
  	<% if content_for?(:title) %>
		<%= yield(:title) %>
	<% else %>
	 	Ticketing System
	<% end %>
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
         <%= link_to "Tickets", root_path, class: "navbar-brand" %>
         <button type="button" class="navbar-toggle collapsed"
           data-toggle="collapse" data-target="#collapse">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
	 </div>

	 <div class="collapse navbar-collapse" id="collapse">
		 <ul class="nav navbar-nav">
		 	<li class="<%= "active" if current_page?("/") %>">
  				<%= link_to "Home", root_path %>
		   	</li>
				<% admins_only do %>
       	<li>
         <%= link_to "Admin", admin_root_path %>
       	</li>
			 <% end %>
		   	<% unless user_signed_in? %>
          	<li class="<%= "active" if current_page?("/users/sign_up") %>">
            	<%= link_to "Sign up", new_user_registration_path %>
          	</li>
          	<li class="<%= "active" if current_page?("/users/sign_in") %>">
            	<%= link_to "Sign in", new_user_session_path %>
          	</li>
        <% end %>
		</ul>

		<% if user_signed_in? %>
      <div class="navbar-right">
        <p class="navbar-text">
          Signed in as <%= current_user.email %>
			  </p>
        <ul class="nav navbar-nav">
          <li><%= link_to "Sign out", destroy_user_session_path,
              method: :delete %>
          </li>
        </ul>
		  </div>
		<% end %>

    </div>
  </div>
</nav>


<div class='container'>

<% flash.each do |key, message| %>
	<div class='alert alert-<%= key %>'>
		<%= message %>
	</div>
<% end %>

<%= yield %>
</div>

</body>
</html>

app/views/tickets/_form.html.erb
<%= simple_form_for([client, ticket]) do |f| %>
    <%= f.input :subject %>
    <%= f.input :details %>
    <%= f.button :submit, class: 'btn-primary' %>
<% end %>

app/views/tickets/edit.html.erb
<header>
	<h1>
		Edit Ticket
		<small><%= @client.name %></small>>
	</h1>
</header>

<%= render "form", client: @client, ticket: @ticket %>

app/views/tickets/new.html.erb
<header>
  <h1>
    New Ticket
    <small><%= @client.name %></small>
  </h1>
</header>
<%= render 'form', client: @client, ticket: @ticket %>

app/views/tickets/show.html.erb
<div id="ticket">
  <header>
    <h1><%= @client.name %></h1>
  </header>
  <header>
    <h2><%= @ticket.subject %></h2>



    <ul class='actions'>
    	<li><%= link_to 'Edit Ticket', [:edit, @client, @ticket], class: 'edit' %></li>
    	<li><%= link_to "Delete Ticket", [@client, @ticket], method: :delete,
	     data: { confirm: "Are you sure you want to delete this ticket?"},
	     class: "delete" %></li>
    </ul>
  </header>

  <table id="attributes">
     <tr>
       <th>Author:</th>
       <td><%= @ticket.author.email %></td>
     </tr>
     <tr>
       <th>Created:</th>
       <td><%= time_ago_in_words(@ticket.created_at) %> ago</td>
      </tr>
  </table>
  <%= simple_format(@ticket.details) %>
</div>